# Generated by Django 3.2.2 on 2021-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jemok', models.CharField(max_length=100)),
                ('sigan', models.DateTimeField(verbose_name='date published')),
                ('naeyong', models.TextField()),
            ],
        ),
    ]
